homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
page2:
    path:     /test
    defaults: { _controller: AppBundle:Default:indexs }
jobCategory:
    path:     /joblisting/{type}
    defaults: { _controller: AppBundle:listing:category }
job_detail:
    path:     /jobDetail/{{id}}
    defaults: { _controller: AppBundle:detail:jobDetail }
